name: Build & Upload
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to crates.io 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install stable rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
      - name: Publish
        run: cargo publish --token ${{ secrets.CARGO_TOKEN }}
  release:
    name: Build on ${{ matrix.target }} and upload
    runs-on: ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      
      
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.3.1
        with:
          toolchain: stable
          
      - name: Linux | Install OpenSSL
        if: runner.os == 'Linux'
        run: sudo apt install libssl-dev
      - name: Compile
        run: cargo build -r
        env:
          OPENSSL_STATIC: 1
         
      - name: Windows | Zip
        uses: vimtor/action-zip@v1
        with: 
          files: target/release/discloud.exe README.md LICENSE
          dest: discloud.zip
        if: runner.os == 'Windows'
        
        
      - name: Linux & Mac | Zip
        uses: vimtor/action-zip@v1
        with: 
          files: target/release/discloud README.md LICENSE
          dest: discloud.zip
        if: runner.os != 'Windows'
  
      - name: Upload zip
        uses: WebFreak001/upload-asset@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ./discloud.zip
          mime: application/zip
          name: discloud-x86_64-${{ runner.os }}.zip
